/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.12.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    kotlin("jvm") version "1.9.0" // Use the latest Kotlin version
    id("com.google.devtools.ksp") version "1.9.0-1.0.13" // Use the latest KSP version
}

repositories {
    mavenCentral()
    google()
}

dependencies {
    implementation("net.dv8tion:JDA:5.0.2") // Add JDA dependency
    implementation("com.google.devtools.ksp:symbol-processing-api:1.9.0-1.0.13") // KSP API

    // KotlinPoet (for generating code)
    implementation("com.squareup:kotlinpoet:2.0.0")
    implementation("com.squareup:kotlinpoet-ksp:2.0.0")
}

kotlin {
    sourceSets.main {
        kotlin.srcDir("build/generated/ksp/main/kotlin")
    }
}


// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

